config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  resources :companies, only: [:index, :show]
  namespace :admin do
    resources :companies do
      resources :service_groups
    end 
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :service_groups

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 280, minimum: 100}
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true
end

app/models/service_group.rb
class ServiceGroup < ApplicationRecord
  belongs_to :company

  validates :title, presence: true, length: {maximum: 50, minimum: 5}
end

app/models/servicegroup.rb
class Servicegroup < ApplicationRecord
  belongs_to :company

  validates :title, presence: true, length: {maximum: 50, minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :companies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_company, only: [:show]

  def new
    @company = Company.new
  end 

  def create
    @company = current_user.companies.create(company_params)
    redirect_to admin_company_path(@company)
  end 

  def show
    @service_group = ServiceGroup.new 
  end 

  private

  helper_method :current_company
  def current_company
    @current_company ||= Company.find(params[:id])
  end 

  def require_authorized_for_current_company
    if current_company.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end 
  end 

  def company_params
    params.require(:company).permit(:name, :description, :address, :phone, :email, :website, :facebook)
  end 
end

app/controllers/admin/service_groups_controller.rb
class Admin::ServiceGroupsController < ApplicationController
  def new
    @company = Company.find(params[:company_id])
    @service_group = ServiceGroup.new 
  end 

  def create
    @company = Company.find(params[:company_id])
    @service_group = @company.service_groups.create(service_group_params)
    redirect_to admin_company_path(@company)
  end 

  private

  def service_group_params
    params.require(:service_group).permit(:title)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end 

  def show
    @company = Company.find(params[:id])
  end 

  private

  helper_method :current_company
  def current_company
    @current_company ||= Company.find(params[:id])
  end 
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @companies = Company.all.sample(6)
    #this is the same as above, for larger database @companies = Company.order("RANDOM()").limit(6)
  end 
  
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/service_groups_helper.rb
module Admin::ServiceGroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/companies/new.html.erb
<div class = add-company-page>
  <br />
  <br />
  <div class="card text-white bg-secondary transparency my-4 text-center col-6 offset-3">
    <div class="card-body">
      <p class="text-white m-0"> We've been waiting on you.</p>
    </div>
  </div>

  <br />
  <br />
  <div class= "col-8 offset-2">
    <h3> Add Your Company </h3>
    <%= simple_form_for @company, url: admin_companies_path do |f| %>
      <%= f.input :name, label: 'Company Name', placeholder: "e.g. My Awesome Company" %>
      <%= f.input :description, placeholder: 'Tell potential clients more about your business. Give your best elevator pitch!' %>
      <%= f.input :address, placeholder: "Clients will depend on this to find you. Make sure it's accurate!" %>
      <%= f.input :phone, placeholder: 'e.g. 1-242-555-555' %>
      <%= f.input :email, label: 'Company Email', placeholder: 'myawesomecompany@domain.com' %>    
      <%= f.input :website, label: 'Company Website', placeholder: 'e.g. https://myawesomecompany.com/' %>
      <%= f.input :facebook, label: 'Company Facebook Page', placeholder: 'e.g. https://www.facebook.com/myawesomecompany/' %>
      <br />
      <%= f.submit "Create", class: 'btn btn-primary' %>
      <br />
    <% end %>
    <br />
  </div>
  <br />
  <div class = "col-10 offset-1">
    <p class: "float-left"><small><i>Photo by <a href="https://unsplash.com/photos/vYpbBtkDhNE?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Eye for Ebony</a> on Unsplash</i></small></p>
  </div>
</div>

app/views/admin/companies/show.html.erb
<div class = "profile-page">
    <br />
    <br />

    <div class="container target">
    <div class="row">
      <div class="col-sm-2">
        <%= image_tag 'barber.jpg', class: 'img-circle' %>
      </div>        
      <div class="col-sm-10">
        <h2 ><%=current_company.name %>&nbsp; &nbsp; <i class="fa fa-facebook-official" aria-hidden="true"></i>&nbsp;<i class="fa fa-external-link" aria-hidden="true"></i></h2>
        <%= link_to 'Edit', '#', class: 'btn btn-success'%>
        <%= link_to 'View Calendar', '#', class: 'btn btn-primary'%>
        <%= link_to 'View Public Page', company_path(current_company), class: 'btn btn-primary'%>
        
        <br>
        <br>
        <p>Location: <%= current_company.address%>
        <br />
        Phone: <%= current_company.phone %> </p>
      </div>

    </div>
  <br>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Activity<i class="fa fa-tachometer pull-right"></i></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Joined: </strong></span><%= current_company.created_at.strftime("%d %b, %y") %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Last seen: </strong></span><%= current_company.user.last_sign_in_at.strftime("%d %b, %y") %></li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Representative: </strong></span>Runako Williams</li>
              <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Role: </strong></span>Barber
               
                      </li>
            </ul>
            <br />
            <ul class="list-group">
                <li class="list-group-item text-muted">Stats<i class="fa fa-line-chart pull-right"></i>

                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Views:</strong></span> 0</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Likes:</strong></span> 0</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Bookings:</strong></span> 0</li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Reviews:</strong></span> 0</li>
            </ul>

        </div>
        <!--/col-3-->
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>About <%= link_to 'Edit', '#', class: 'pull-right btn btn-success btn-sm' %></h3></div>
                <br />
                <div class="panel-body"> <p><%= current_company.description %></p>

                </div>
            </div>
            <br />
            <div class="panel panel-default target">
                <div class="panel-heading" contenteditable="false"><h3>Photos <%= link_to 'Add Photos', '#', class: 'pull-right btn btn-success btn-sm' %></h3></div>

<!--                  Carousel goes here  
 -->
            </div>
            <br />
            <br />
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Services 
                    <!-- Button trigger modal -->
                        <button type="button" class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#newServiceGroupModal">
                          Add Service Category
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="newServiceGroupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h6 class="modal-title" id="newServiceGroupModal">Add A Service Category &nbsp;&nbsp;</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true"> x </span>
                                </button>
                              </div>
                            <%= simple_form_for @service_group, url: admin_company_service_groups_path(current_company) do |f| %>
                              <div class="modal-body">
                                    <%= f.input :title, label: 'Service Group Title', placeholder: "e.g. Hair Braiding" %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                <%= f.submit "Add Service Group", class: 'btn btn-success' %>
                              </div>
                            <% end %>  
                            </div>
                          </div>
                        </div>
<!--                     Modal ends      -->
                </h3>
            </div> 
                <div class="panel-body"> 
                    <p> 
                        <% current_company.service_groups.each do |service_group| %>
                            <%= service_group.title %>
                            <br />
                        <% end %>
                    </p>
                </div>
            </div>
            <br />
            <br />
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Reviews</h3></div>
                <div class="panel-body"> <p>List of reviews</p>
                </div>
            </div>

          </div>


            <div id="push"></div>
        </div>
    </div>
</div>

app/views/admin/servicegroups/new.html.erb
<br />
<br />

<br />
<br />
<div class= "col-8 offset-2">
<h3> Add A Service Group </h3>
<br/>
  <%= simple_form_for @service_group, url: admin_company_service_groups_path(@company) do |f| %>
    <%= f.input :title, label: 'Service Group Title', placeholder: "e.g. Hair Braiding" %>
    <br />
    <%= f.submit "Add Service Group", class: 'btn btn-primary' %>
    <br />
  <% end %>
<br />


</div>

<br />

app/views/companies/index.html.erb
<div class = "company-list-page col-12">
  <br /> 
  <br />
  <h3 class="text-center">Choose From A Wide Range of Vendors</h3>
  <hr />

  <!-- Content Row 1-->
  <div class = "col-12">
      <div class = "container">
        <div class="row">    
          <% @companies.each do |company| %>
            <div class="col-12 col-md-4 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <h5 style="color:#D64541;" class="card-title"><%= company.name %></h5>
                  <p class="card-text"><%= company.description %></p>
                </div>
                <div class="card-footer">
                  <%= link_to 'View Services', company_path(company), class: "btn btn-primary" %>
                </div>
              </div>
            </div>
<!--             <br class = "clr" /> -->
          <% end %>
        </div>
      </div>
  </div>


  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br /> 
  <div class= "col-10 offset-1">
    <p class: "float-left"><small><i>Photo by <a href="https://unsplash.com/@auttgood">Autumn Goodman</a> on Unsplash</i></small></p>
  </div>
</div>

app/views/companies/show.html.erb
<div class = "profile-page">
    <br />
    <br />
    <div class="container target">
        <div class="row">
          <div class="col-sm-2">
            <%= image_tag 'barber.jpg', class: 'img-circle' %>
          </div>        
          <div class="col-sm-10">
            <h2 ><%=current_company.name %>&nbsp; &nbsp; <i class="fa fa-facebook-official" aria-hidden="true"></i>&nbsp;<i class="fa fa-external-link" aria-hidden="true"></i></h2>
            <% if current_user && current_user == current_company.user %>
              <%= link_to 'View Admin Page', admin_company_path(current_company), class: 'btn btn-success'%>
              <br />
              <br />        
            <% end %>
            <p>Location: <%= current_company.address%>
            <br />
            Phone: <%= current_company.phone %> </p>
          </div>

    </div>
  <br>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Stats<i class="fa fa-line-chart pull-right"></i></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Joined: </strong></span><%= current_company.created_at.strftime("%d %b, %y") %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Likes:</strong></span> 0</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Total Reviews:</strong></span> 0</li>   
                <li class="list-group-item text-right"><span class="pull-left"><strong class="list-subheader">Average Review:</strong></span> 0</li>             
            </ul>
            <br />

        </div>
        <!--/col-3-->
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>About</h3></div>
                <br />
                <div class="panel-body"> <p><%= current_company.description %></p>

                </div>
            </div>
            <br />
            <div class="panel panel-default target">
                <div class="panel-heading" contenteditable="false"><h3>Photos <%= link_to 'View All', '#', class: 'pull-right btn btn-success btn-sm' %></h3></div>

<!--                  Carousel goes here  
 -->
            </div>
            <br />
            <br />
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Services</h3></div> 
                <div class="panel-body"> <p> List of services</p>
                </div>
            </div>
            <br />
            <br />
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Reviews</h3></div>
                <div class="panel-body"> <p>List of reviews</p>
                </div>
            </div>

          </div>


            <div id="push"></div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NKS Style</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-light fixed-top">
      <div class="container">
        <%= link_to 'NKS STYLE', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">        
            <%= link_to 'About', about_path, class: 'nav-link' %>
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <%= link_to 'Services', '#', class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Vendors', companies_path, class: 'nav-link' %>
            </li>  
            &nbsp;          
            <li class="nav-item">
              <%= link_to 'Add Your Company', new_admin_company_path, class: 'btn btn-primary' %>
            </li>
            &nbsp;
            &nbsp;
            <% if user_signed_in? %>
              <li class="nav-item">     
                <%= link_to 'Sign Out', destroy_user_session_path(@user), method: :delete, class:'btn btn-primary' %>
              </li>
            <% else %>
              <li>
                <%= link_to "Log In", new_user_session_path, class:'btn btn-primary' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    <!-- Footer -->
    <!-- <div id="footer">
      <div class="container">
        <b> N K S For Companies </b>
        <br />
        <%= link_to 'Manage Your Company', '#' %>
        <br />
        <%= link_to 'Contact Us', '#' %>
      </div>
    </div> -->
  </body>

</html>

app/views/static_pages/about.html.erb
<br />
<br />
<div class = 'col-10 offset-1'>
  <h3> About test page </h3>
  <br />
</div>

app/views/static_pages/index.html.erb
  <body class = "home-page">

    <!-- Page Content -->
    <div class="container">

      <!-- Heading Row -->
      <div class="row my-4">
        <div class="col-lg-8">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <%= image_tag 'makeup2.jpg', class: 'd-block img-fluid' %>
              </div>
              <div class="carousel-item">
                <%= image_tag 'nails.jpg', class: 'd-block img-fluid' %>
              </div>
              <div class="carousel-item">
                <%= image_tag 'barber.jpg', class: 'd-block img-fluid' %>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
          <br/>
          <h2><b>Your Source For The Best in Fashion &amp; Beauty</b></h2>
          <p> The NKS Style website allows you to easily connect and make bookings with your next hair stylist, barber, nail tech, dress designer, and so much more!</p>
          <%= link_to 'Sign Up Free', new_user_registration_path, class: "btn btn-primary btn-lg" %>
        </div>
        <!-- /.col-md-4 -->
      </div>
      <!-- /.row -->

      <!-- Call to Action Well -->
      <div class="card text-white bg-secondary transparency my-4 text-center">
        <div class="card-body">
          <p class="text-white m-0"> Sign Up for a FREE<span class="logo"> NKS STYLE </span>account to connect your business to new and existing clients. &nbsp; <%= link_to "Learn More", about_path, class: 'btn btn-primary' %> </p>
        </div>
      </div>

      <!-- Content Row 1-->
      <div class="row">
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[0].name %></h5>
              <p class="card-text"><%=@companies[0].description %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary"> View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[1].name %></h5>
              <p class="card-text"><%=@companies[1].description %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[2].name %></h5>
              <p class="card-text"><%=@companies[2].description %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->

      </div>
      <!-- /.row -->


            <!-- Content Row 2 -->
      <div class="row">
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[3].name %></h5>
              <p class="card-text"><%=@companies[3].description %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[4].name %></h5>
              <p class="card-text"><%=@companies[4].description %> %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><%=@companies[5].name %></h5>
              <p class="card-text"><%=@companies[5].description %></p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">View Services</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <%= yield %>
  </body>